const fs = require('fs');
const path = require('path');

const contractsDir = path.join(__dirname, '../contracts');
const frontendDir = path.join(__dirname, '../frontend');

function main() {
  console.log('Syncing contracts and ABIs to frontend...');

  // 1. Find the deployed factory address from broadcast files
  const broadcastDir = path.join(contractsDir, 'broadcast/Deploy.s.sol');
  let factoryAddress = '';

  if (fs.existsSync(broadcastDir)) {
    const chainIds = fs.readdirSync(broadcastDir);
    for (const chainId of chainIds) {
      const runLatestPath = path.join(broadcastDir, chainId, 'run-latest.json');
      if (fs.existsSync(runLatestPath)) {
        try {
          const runData = JSON.parse(fs.readFileSync(runLatestPath, 'utf8'));
          const deployTx = runData.transactions.find(
            (tx) => tx.transactionType === 'CREATE' && tx.contractName === 'CoffeeFactory'
          );
          if (deployTx && deployTx.contractAddress) {
            factoryAddress = deployTx.contractAddress;
            console.log(`Found CoffeeFactory deployed on chain ${chainId} at: ${factoryAddress}`);
            break; 
          }
        } catch (e) {
          console.error(`Error reading ${runLatestPath}:`, e.message);
        }
      }
    }
  }

  // 2. Prepare output directories in frontend
  const constantsDir = path.join(frontendDir, 'src/constants');
  const abiDir = path.join(constantsDir, 'abi');

  if (!fs.existsSync(constantsDir)) {
    fs.mkdirSync(constantsDir, { recursive: true });
  }
  if (!fs.existsSync(abiDir)) {
    fs.mkdirSync(abiDir, { recursive: true });
  }

  // 3. Write addresses.ts
  const addressesFilePath = path.join(constantsDir, 'addresses.ts');
  const fileContent = `// Automatically generated by scripts/sync.js. Do not edit manually.
export const COFFEE_FACTORY_ADDRESS = "${factoryAddress || '0x0000000000000000000000000000000000000000'}";
`;
  fs.writeFileSync(addressesFilePath, fileContent, 'utf8');
  console.log(`Updated factory address in: ${addressesFilePath}`);

  // 4. Sync ABIs
  const artifactsToSync = [
    { name: 'CoffeeFactory', pathName: 'CoffeeFactory.sol/CoffeeFactory.json' },
    { name: 'BuyMeACoffee', pathName: 'BuyMeACoffee.sol/BuyMeACoffee.json' }
  ];

  for (const artifact of artifactsToSync) {
    const artifactPath = path.join(contractsDir, 'out', artifact.pathName);
    if (fs.existsSync(artifactPath)) {
      try {
        const fullJson = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
        const abiOnly = { abi: fullJson.abi };
        const outPath = path.join(abiDir, `${artifact.name}.json`);
        fs.writeFileSync(outPath, JSON.stringify(abiOnly, null, 2), 'utf8');
        console.log(`Synced ABI for ${artifact.name} to ${outPath}`);
      } catch (e) {
        console.error(`Failed to process ABI for ${artifact.name}:`, e.message);
      }
    } else {
      console.warn(`Artifact not found: ${artifactPath}`);
    }
  }

  console.log('Contract ABI and Address syncing complete!');
}

main();
